worker_processes auto;
daemon off;
pid nginx.pid;
error_log /dev/null crit;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type text/plain;
    access_log off;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 8080;
        server_name localhost;
        access_log off;

        location = /test {
            return 200 "Hello World";
        }
    }
}
